### ISSUE TITLE
Could a wiki page be made regarding what to do when new characters come out?

### ISSUE THREAD

**Issue by SiiNerGia** [WAZAAAAA0/TekkenBot#13]
Hello, I have already seen you have a wiki page with a tutorial on how to update the bot when a new patch comes out. However, it doesn't include what to do when new characters come out and I guess updating the adresses is not everything that has to be done, since Negan is missing some frame data. Could you make a wiki page explaining how to introduce the frame data for new moves and characters? Thank you.

**Comment by WAZAAAAA0** [comment]
uhh I don't do anything in particular for new characters, the frame data addresses used by the program are universal

**Comment by SiiNerGia** [comment]
So whenever a new patch with new characters comes out you just need to update the adresses? Then why is Negan missing moves?

**Comment by WAZAAAAA0** [comment]
the fuck do I know the motherfucker is DLC can't even use him
