### ISSUE TITLE
Error 299 ver. 15.0

### ISSUE THREAD

**Issue by Anoncrack** [WAZAAAAA0/TekkenBot#18]
Gettin this error with new version of Tbot.
Game is updated. Steam is updated.
Any recommendation?

**Comment by Anoncrack** [comment]
Nevermind. TekkenBot have this error but its working

**Comment by compsyguy** [comment]
Quick question about this bug - since its one I want to look at next week - does it only happen when not in an actual match?

**Comment by Sam-Si** [comment]
@compsyguy This happens only when there is no actual battle going on.
For example: Loading screen, menu screen etc...
