### ISSUE TITLE
Multi-level null pointer

### ISSUE THREAD

**Issue by Alchemy-Meister** [WAZAAAAA0/TekkenBot#19]
https://github.com/WAZAAAAA0/TekkenBot/blob/3aa14ee69ab5e0e8569022cafc402d9c80c52918/TekkenGameState.py#L191

add the following in line 192:
if not value:
    break

**Comment by WAZAAAAA0** [comment]
(adding more details about this issue)

the latest update to `TekkenGameState.py` added support for additional address offsets, but now running the bot in menus reports error 299
```
Tekken pid acquired: 3208
Trying to acquire Tekken library in pid: 3208
Found TekkenGame-Win64-Shipping.exe
ReadProcessMemory Error: Code 299
Tekken pid acquired: 3208
Trying to acquire Tekken library in pid: 3208
Found TekkenGame-Win64-Shipping.exe
ReadProcessMemory Error: Code 299
```
and the suggested solution doesn't fix it
```
add the following in line 192:
if not value:
break
```
It doesn't really matter though, the bot still works normally during actual gameplay

**Comment by WAZAAAAA0** [comment]
changed the error message to be a bit friendlier, hopefully it will stop scaring people away https://github.com/WAZAAAAA0/TekkenBot/commit/14d380d5169c92d7a12080586b7512779a32558c
