### ISSUE TITLE
Getting error 299 when starting up

### ISSUE THREAD

**Issue by pakirambo** [WAZAAAAA0/TekkenBot#23]
Started tekkenbot as admin, started tekken got the error.
![TekkenBotPrime_aXqoUaMiD4](https://user-images.githubusercontent.com/66361158/83621770-8c96c000-a5a8-11ea-8db1-24080c20795d.png)

**Comment by compsyguy** [comment]
That's typical with the current build, it should go away when you get into a match. Right now its such a minor thing, its more effort to fix it then its worth.

**Comment by WAZAAAAA0** [comment]
duplicate of https://github.com/WAZAAAAA0/TekkenBot/issues/19
