### ISSUE TITLE
Switched sides 

### ISSUE THREAD

**Issue by AIIfather** [WAZAAAAA0/TekkenBot#25]
If I have to use the Punish alarm mode, or the Command inputs mode in Tekken Bot Prime, I have to select the right side before a match, or even in practice mode. If I select the left side, it won't alert me for punishes or won't show my command inputs. Is there a way to switch to P1 in Tekken Bot Prime so that it registers my command inputs and alerts me for punishing the opponent's unsafe moves and not vice versa?

Thanks!

**Comment by WAZAAAAA0** [comment]
try FimoX' update, one of the addresses that changed with 3.33 is `OPPONENT_SIDE`  https://raw.githubusercontent.com/FimoX/TekkenBot/patch-4/TekkenData/memory_address.ini
to be honest I haven't bothered applying that update to the bot because a huge patch is coming soon anyway

**Comment by AIIfather** [comment]
Thanks a lot, bud. I can confirm that the switched sides thing is fixed now. However, and I'm sure you must already know this, but, many of the commands done in the game are shown incorrectly in Tekken Bot Prime.  Like, for example, King's f2, d1, f2 is shown incorrectly. I don't remember exactly what the command shown was, but it was different, so were some others, for other characters. Is this just a bug or is there any other reason for this?

**Comment by WAZAAAAA0** [comment]
Good.
it has been like that for as long as I can remember, whoever wants to try and fix it is welcome
