### ISSUE TITLE
Optional: please consider making it compatible with wine

### ISSUE THREAD

**Issue by janicolou** [WAZAAAAA0/TekkenBot#26]
![image](https://user-images.githubusercontent.com/68493723/93866068-c9262d00-fcf9-11ea-8bb9-207d37e19b78.png)

**Comment by compsyguy** [comment]
It is open source, so you could try and tackle that yourself.... also it is written in python, so you could just run the script without the executable.

**Comment by d-allison** [comment]
Hi,
I'm writing this in the hopes that somebody else looking to do the same thing might save some time.
The previous commenter is, from my findings, incorrect—you _can_ run the script natively with a python interpreter, but you'll immediately notice an error arising from PIDSearcher.py. This file immediately loads a DLL which doesn't even exist on Linux (or BSD I would imagine). Alternatively, you might try to load the Windows executable with Wine, but you'll notice that the program forever hunts for the Tekken 7 PID; you're likely running TekkenBot with a different Wine prefix than Steam is using to run Tekken, so the two processes can't see each other. I, after an embarrassing amount of time, did manage to get around this.

Here's what I had to do to "fix" the issue (using Proton >5.13):
I'm assuming you already have a functional Proton setup. If not, there are better guides than I can write elsewhere. Valve has made it rather trivial for us to set up, fortunately.
1. Install [SteamTinkerLaunch](https://github.com/frostworx/steamtinkerlaunch)
- I personally found that the most recent release wasn't working for me, but I was also very tired and possibly overlooking something silly. I'm testing with stl-v7.0
- My version of SteamTinkerLaunch has its binary named "stl", but later versions renamed this to "steamtinkerlaunch". Anywhere you see "stl", you can substitute for the newer command if you're running the newer version. The behaviour should be the same.
2. Run `stl compat add` to add Steam Tinker Launch as a compatibility "runner".'
3. Restart Steam (or launch it if it wasn't already running)
4. Go into your Steam library and right-click on Tekken 7 to open Properties -> Compatability. You'll want to select "Force the use of a specific Steam Play compatibility tool", and then select "Steam Tinker Launch" in the drop-down below.
5. Now when you launch Tekken, another window will open before the game's main executable runs. You'll want to click on "Main Menu".
- This is the main menu (shocking I know) of Steam Tinker Launch. There's a lot to do here if you're interested. They have an excellent wiki on their repository page.
6. Click "Game Menu"
7. Scroll on down to "Proton options". Here you'll want to:
- Deselect "Use Steam Linux Runtime"
- Deselect "Use reaper command"
- Select "Proton no ESYNC"
Steam Linux Runtime is, by my understanding, what's preventing us from running other programs using the same Wine prefix as Steam. I have no idea what the reaper is, but turning it off made things work.
As for ESYNC, I'd prefer to have that on, but it'll cause an issue later when we go to run TekkenBot. It might be possible to get around this, and if I find a way to do that I'll add details later.
8. Click "Save and Play"
9. Change directories to wherever you extracted TekkenBotPrime to (remember, we're using the Windows release. You really don't want the added headache of installing Python in this Wineprefix and then running it through an interpreter; make use of the work that's been done for us)
10. You'll need to run TekkenBotPrime.exe using the same wine executable as that being used by Steam (not really Steam at this point, but who cares)
For me, this is located at `/home/my_user_name/.steam/steam/steamapps/common/Proton\ 6.3/dist/bin/wine64` but you might be using a different Proton version, so just keep that in mind.
For reference, the full command looks like `/home/lia/.steam/steam/steamapps/common/Proton\ 6.3/dist/bin/wine64 TekkenBotPrime.exe` for me

For the project managers: I'd personally go ahead and close this issue—there's nothing on your end to do with regards to Linux compatibility as far as I'm aware. I hate to say this, but I can't imagine the work you'd have to do to ship a Linux executable would be worth it given how easy this work around is and that we'll be running Tekken in Wine regardless.
Thanks for maintaining this tool, it's been very helpful to me!
