### ISSUE TITLE
How do I update memory addresses

### ISSUE THREAD

**Issue by ComputerMachine** [WAZAAAAA0/TekkenBot#29]
The README says there's an article explaining how to update addresses. I'd like to help and contribute to this project but I'm not quite sure how, I need some direction.

I'd like to update all the memory addresses, some are still invalid after the newest patch, like complex_states.

**Comment by WAZAAAAA0** [comment]
well, did you try reading said article? <https://github.com/WAZAAAAA0/TekkenBot/wiki/How-to-update-addresses>
speaking of addresses that are still invalid, the proper `char_id` is `0xD8`. Oops

**Comment by ComputerMachine** [comment]
Nah bud I couldn't find the wiki. Hardly ever use github but thanks.

**Comment by ComputerMachine** [comment]
I've followed the tutorial exactly and when I do a pointer scan I don't get any results. Is it possible the offset is different than what it says in the video, which was 31C?

**Comment by thoraero** [comment]
Can I ask for some advice here?
In prior release, I could access the memory, using CE, with "TekkenGame-Win64-Shipping.exe"+0x0XXXXXXX (player offset) and adding a layer of the specific offsets, such as move id, in [PlayerDataAddress].
But somehow in 5.1 somehow I can no longer do the same. Can anyone pls enlighten me about this?

**Comment by WAZAAAAA0** [comment]
those offsets are indeed outdated, the video is only helpful for navigating CE's interface at this point
