### ISSUE TITLE
TekkenEncyclopedia(ThrowBreakVersion) Not Doing Anything?

### ISSUE THREAD

**Issue by Xalraroz** [WAZAAAAA0/TekkenBot#32]
what im supposed to do with it? its not working. The CMD Prompt just pops up and closes for a split second.

**Comment by WAZAAAAA0** [comment]
you gotta replace the regular version of the file with the modded one, like this

rename
`TekkenEncyclopedia.py` to `TekkenEncyclopedia.py.BAK`
and
`TekkenEncyclopedia(ThrowBreakVersion).py` to `TekkenEncyclopedia.py`
finally run the bot normally from `GUI_TimelineOverlay.py`. Your character should now automatically press the corresponding keyboard button to break throws

**Comment by Xalraroz** [comment]
ok i did that but nothing is happening the cmd pops up and closes

**Comment by Xalraroz** [comment]
nvm its working
