### ISSUE TITLE
Throwbreak not working?

### ISSUE THREAD

**Issue by rajnmaker** [WAZAAAAA0/TekkenBot#38]
TekkenEncyclopedia.py
finally run the bot normally from GUI_TekkenBotPrime.py. Your character should now automatically press the corresponding keyboard button to break throws

I changed it like this and launched GUI_TekkenBotPrime.py but nothing's working

**Comment by WAZAAAAA0** [comment]
duplicate of https://github.com/WAZAAAAA0/TekkenBot/issues/32, can't reproduce, likely outdated by now (reopen the older issue if necessary)
