### ISSUE TITLE
Not able to capture frame data

### ISSUE THREAD

**Issue by adnanal911** [WAZAAAAA0/TekkenBot#4]
I tried running game in window mode and even borderless but i am not able to capture frame data and i do get 60fps while playing. I am running Fit Girl Repack V1.06. Please let me know where am i making a mistake. TIA

**Comment by compsyguy** [comment]
TekkenBot won't likely run on cracked versions.

**Comment by WAZAAAAA0** [comment]
it reads the memory yes but a patch that changes a single byte of the game can potentially force you to find all the addresses again
so someone would need to make a 1.06 compatible `memory_address.ini`

**Comment by adnanal911** [comment]
Well I'm not a programmer incase if you found any please do let me know and thank you for your reply greatly appreciate 😊

**Comment by adnanal911** [comment]
hwo to find memory address with cheat engine??
