### ISSUE TITLE
correcting frame data

### ISSUE THREAD

**Issue by choi-choi** [WAZAAAAA0/TekkenBot#5]
hi guys,

can we as end users manually change the frame data values for the characters? i found some mistakes for kazuya for example. a perfect electric is 13 frames, however any electric or wind god fist says 11.

not sure if there is a file where this all refers to and i can edit maybe in notepad or something.

thanks!

**Comment by yup-yup** [comment]
WAZAAAAA0, you need to add inputs for some moves

**Comment by WAZAAAAA0** [comment]
apples and oranges
