### ISSUE TITLE
How fix the size !!

### ISSUE THREAD

**Issue by HeiUserGG** [WAZAAAAA0/TekkenBot#8]
I want to fix the size of the window size !!

It is too much trouble to resize after restart...

Update PLZ !!

**Comment by WAZAAAAA0** [comment]
change it for yourself in `GUI_Overlay.py`. Look for `self.w = ` and change them to the numbers you want, like this
```
self.w = 1000
self.h = 100
```
you'll need to run TBP from the `GUI_TekkenBotPrime.py` source file instead of the compiled `TekkenBotPrime.exe` from now on
