### ISSUE TITLE
replay file format suggestion

### ISSUE THREAD

**Issue by Labreezy** [WAZAAAAA0/TekkenBot#9]
This format needs to be parsed and emulated at 60 fps, so after looking at the current replay code, i'd like the reads and writes and parses to be as simple as possible.

 What we'll need from the game's memory while recording:
both player's input buffers (may or may not be possible for remote player)
*maybe* local player's side selection just in case

 Implementation:

1,2,4,8 = U,R,D,L (XInput does it up clockwise, R is backwards for 2P side (if more convenient))
0x10, 0x20, 0x40, 0x80 = 1,2,3,4

Logical AND the bytes together to create a frame.

Special codes: either 0x05 0x00 to signal that left side won (p1 side) or 0x0A 0x00 for right side won (round-to-round for sanity checks), U/D and L/R are 0x05 and 0x0A, can't happen so are "magic" in that sense.

so you'd have [P1] [P2] [P1] [P2] ..... [P1] [P2] [05 or 0A] [00]

 I'd be glad to throw something together/use some CE magic to do some input buffer finding.

**Comment by taneltm** [comment]
What about RA and Assist button?

**Comment by WAZAAAAA0** [comment]
The dude who opened this issue has gone to make his own replay solution, check it out here https://github.com/Labreezy/TekkenReplayUtil
